const fs = require('fs');
const path = require('path');

console.log('🤖 DROID Setup Assistant');
console.log('========================');
console.log('');
console.log('DROID uses Groq API (FREE) for cloud AI processing.');
console.log('To get started:');
console.log('');
console.log('1. Go to: https://console.groq.com/keys');
console.log('2. Create a free account');
console.log('3. Generate an API key');
console.log('4. Set your API key:');
console.log('');
console.log('   Windows: set GROQ_API_KEY=your_api_key_here');
console.log('   macOS/Linux: export GROQ_API_KEY=your_api_key_here');
console.log('');
console.log('Alternative: Install Ollama locally for private AI');
console.log('- Windows: Download from https://ollama.com');
console.log('- Run: ollama pull llama3.2:3b');
console.log('- Toggle to LOCAL mode in DROID');
console.log('');
console.log('Then run: npm run dev');
console.log('');